# Generated by Django 4.1.7 on 2023-06-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='membership',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
